export default{
    products:[
      {
        id:1,
        title:"turquoise Mulberry Silk Pillowcase",
        category: 'coussin',
        image: "images/turquoise copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      },  
      {
        id:2,
        title:"dark-blue Mulberry Silk Pillowcase",
        category: 'coussin',
        image: "images/dark-blue copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      } ,
      {
        id:3,
        title:"ivory Mulberry Silk Pillowcase",
        category: 'coussin',
        image: "images/ivory copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      },
      {
        id:4,
        title:"pink Mulberry Silk Pillowcase",
        category: 'coussin',
        image: "images/pink copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      } ,
      {
        id:5,
        title:"purple Mulberry Silk Pillowcase",
        category: 'coussin',
        image: "images/purple copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      },
      {
        id:6,
        title:"ivory Mulberry Silk Pillowcase",
        category: 'coussin',
        image: "images/ivory-white copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      }       
    ]
}