export default{
    products:[
      {
        id:1,
        title:"turquoise Mulberry Silk Pillowcase",
        category: 'coussin',
        image: src="images/turquoise copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      },  
      {
        id:1,
        title:"turquoise Mulberry Silk Pillowcase",
        category: 'coussin',
        image: src="images/dark-blue copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      } ,
      {
        id:1,
        title:"turquoise Mulberry Silk Pillowcase",
        category: 'coussin',
        image: src="images/ivory copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      },
      {
        id:1,
        title:"turquoise Mulberry Silk Pillowcase",
        category: 'coussin',
        image: src="images/pink copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      } ,
      {
        id:1,
        title:"turquoise Mulberry Silk Pillowcase",
        category: 'coussin',
        image: src="images/purple copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      },
      {
        id:1,
        title:"turquoise Mulberry Silk Pillowcase",
        category: 'coussin',
        image: src="images/ivory-white copy.png",
        price:40,
        rating:5,
        numReviews:100,
        countInstock: 100,
      }       
    ]
}